### ISSUE TITLE
Maps in BibleBrowser

### ISSUE THREAD

**Issue by KenBitgood** [digitalbiblesociety/browserbible#7]
We would like to add another media type to include maps in the BibleBrowser that function identical to the photos and the videos icons.
We organically thought these may be included under the photos, but in light of there being over 139 maps, it seems more appropriate to have their own icon. 

Nathan is in the process of creating the Json.

We will need to include the on / off feature in the Settings.

Icon that looks like this may be nice: 
http://d23b32zmhbr2ct.cloudfront.net/images/extend/icon_map_mashups_small.png

**Comment by johndyer** [comment]
Jon,
I was thinking you might be able to copy what I did for images. What do you think?

You'd need to make a new plugin, add the icon to the CSS, and create a folder called /content/maps/
