### ISSUE TITLE
Feature: BibleReference HoverOver Pop Up

### ISSUE THREAD

**Issue by KenBitgood** [digitalbiblesociety/browserbible#8]
It would be most helpful if a user upon HoverOver of a Bible Reference inside a Bible or Book (such as the TSK) would see a pop up of that verse.

An great example of this is the Logos Ref Tagger at  http://www.logos.com/reftagger.

Upon moving the mouse off the verse, the popup would quickly fade out. 
Or, if moving the mouse from one reference to another, the verse in the popup would change.
And, upon mouse click on the verse, Sofia would load that verse into the Browser.

**Comment by johndyer** [comment]
Ken,
I just happened to be checking this this morning and noticed you added this issue. Right now, I don't get an email if an issues is added, so I need to figure out how to do that so I can track this stuff. This is an idea I just started working on last week as I got a copy of TSK to add in.

Sofia? :)

**Comment by KenBitgood** [comment]
Hey John,
Great to hear!  Cant wait to use the best reference tool in the world!
Shall I send an email of a posting? I do like to be able to add stuff here
where we can track progress.
Ken

P.S. Made you smile ;)

On 6/30/12 8:13 AM, "John Dyer"
<reply+i-5367270-b7c738d658c867dc89a3d609ed186b43ce7909f4-1375154@reply.git
hub.com> wrote:
